services:
  mc:
    image: itzg/minecraft-server
    container_name: paper
    environment:
      EULA: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 7
      MEMORY: 7G
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    restart: unless-stopped
  playit:
    container_name: playit
    image: ghcr.io/mafen/playit-docker:latest
    restart: unless-stopped
    environment:
      -  PLAYIT_SECRET=
    volumes:
      - playit/config:/etc/playit
volumes:
  mc-paper: {}
