services:
  mc:
    image: itzg/minecraft-server
    container_name: paper
    environment:
      EULA: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 7
      MEMORY: 7G
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    restart: unless-stopped
  playit:
    image: ghcr.io/playit-cloud/playit-agent:0.15
    network_mode: host
    environment:
      -  SECRET_KEY=6a5b199fbe28e8bf6c4dccb8d9e64701385be27b67eaf36161f82d2927ac8598
volumes:
  mc-paper: {}
