services:
  mc:
    image: itzg/minecraft-server
    container_name: paper
    environment:
      EULA: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 10
      MEMORY: 7G
    ports:
      - "25565:25565"
    volumes:
      - ./data:/data
    restart: unless-stopped
volumes:
  mc-paper: {}
